# Generated by Django 4.2.4 on 2023-08-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik_id', models.CharField(max_length=10)),
                ('name_of_issuer', models.CharField(max_length=255)),
                ('cusip', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shares', models.CharField(max_length=100)),
                ('investment_discretion', models.CharField(max_length=20)),
                ('voting_info', models.CharField(max_length=100)),
                ('quarter_info', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FundCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=255)),
                ('cik_id', models.CharField(max_length=10)),
            ],
        ),
    ]
